name: Node.js CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest #指定运行环境为最新的Ubuntu版本
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: Use Node.js 14.x #使用action安装node环境
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'yarn'
    - name: build
      run: |
        git clone https://github.com/troyeguo/koodo-reader.git
        cd koodo-reader
        yarn
        yarn build
        
        
