name: Node.js CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest #指定运行环境为最新的Ubuntu版本
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: Use Node.js 14.x #使用action安装node环境
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install -g yarn
    - name: build
      run: |
        bash build.sh
      
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -- . ':!koodo-reader'
        git commit -m "更新时间 $(date '+%Y-%m-%d %H:%M:%S')"
        git push origin main
